
# install tools to build app
# install depencies libraries and packages
# build you application

FROM debian

# set up
RUN apt-get update
RUN apt-get install -y
RUN apt-get install python3-pip -y
RUN pip3 install django 


# create workdirectory
WORKDIR jamie

