# Generated by Django 2.1.2 on 2018-10-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('collateral_location', models.URLField(max_length=255)),
                ('version', models.FloatField()),
            ],
        ),
    ]
