# Generated by Django 2.1.3 on 2018-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
