# Generated by Django 2.1.3 on 2018-11-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0002_newsitem_is_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
