# Generated by Django 2.1.2 on 2018-10-17 06:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('date_received', models.DateField(blank=True, default=datetime.datetime.now)),
                ('current_status', models.CharField(choices=[('Awaiting triage', 'Awaiting triage'), ('Awaiting scoping and costing', 'Awaiting scoping and costing'), ('Awaiting data retrieval and analysis', 'Awaiting data retrieval and analysis'), ('Awaiting approval', 'Awaiting approval'), ('Awaiting confirmation of completed work', 'Awaiting confirmation of completed work'), ('Closed', 'Closed'), ('On hold', 'On hold')], max_length=255)),
                ('has_associated_cost', models.BooleanField()),
                ('quoted_cost', models.FloatField()),
                ('date_due', models.DateField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(max_length=255)),
                ('title_or_summary', models.CharField(max_length=255)),
                ('data_supplied', models.BooleanField(default=True)),
                ('requestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField()),
                ('title_or_summary', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('task_type', models.CharField(choices=[('Scoping and costing', 'Scoping and costing'), ('Data retrieval and analysis', 'Data retrieval and analysis'), ('Approval', 'Approval')], max_length=255)),
                ('task_detail', models.TextField()),
                ('task_completed', models.BooleanField(default=False)),
                ('days_required', models.IntegerField()),
                ('request', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
