# Generated by Django 2.1.2 on 2018-10-17 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='allocated_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_task_allocated_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_task_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
